#!/usr/bin/env python3
"""Generate the Governance requirements index."""
from __future__ import annotations
import argparse
import re
import sys
from pathlib import Path

FILES = [
    "NORMATIVE-LANGUAGE.md", "DOCUMENT-LIFECYCLE.md", "DOCUMENT-METADATA.md",
    "VERSIONING.md", "CHANGE-PROCESS.md", "EXCEPTIONS.md", "COMPLIANCE.md",
]
ROW = re.compile(r"^\|\s*`?(SASD-GOV-REQ-\d{3})`?\s*\|\s*(.*?)\s*\|\s*$")


def generate(repo: Path) -> str:
    folder = repo / "docs" / "40-governance"
    rows = []
    for name in FILES:
        text = (folder / name).read_text(encoding="utf-8")
        for line in text.splitlines():
            m = ROW.match(line)
            if m:
                rows.append((m.group(1), name, m.group(2)))
    header = """---
title: "Governance Requirements Index"
document-id: SASD-REF-GOV-004
document-type: informative
status: Draft
version: 0.8.0
standard-version: "1.0"
language: de
authoritative: false
owner: SASD Development Standard Maintainer
last-updated: 2026-07-24
applies-to-quality-levels: [Minimum, Recommended, Production]
applies-to-profiles: [Core, DotNet, Desktop]
depends-on: [SASD-GOV-001, SASD-GOV-002, SASD-GOV-003, SASD-GOV-004, SASD-GOV-005, SASD-GOV-006, SASD-GOV-007]
normative-keywords: []
generated: true
---

# Governance Requirements Index

> Generated by `tooling/generate-governance-requirements-index.py`. Do not edit manually.

| Requirement ID | Source | Requirement |
|---|---|---|
"""
    body = "\n".join(f"| `{rid}` | [{name}]({name}) | {statement} |" for rid, name, statement in rows)
    return header + body + f"\n\n**Total:** {len(rows)} Governance requirements.\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    repo = Path(__file__).resolve().parents[1]
    target = repo / "docs" / "40-governance" / "GOVERNANCE-REQUIREMENTS-INDEX.md"
    expected = generate(repo)
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != expected:
            print("FAIL Governance requirements index is not current")
            return 1
        print("OK   Governance requirements index is current")
        return 0
    target.write_text(expected, encoding="utf-8")
    print(f"Generated {target.relative_to(repo)}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
