#!/usr/bin/env python3
"""Generate an informative index of all SASD Desktop profile requirements."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

FILES = ["DESKTOP-PROFILE.md", "UI-ARCHITECTURE.md", "USER-EXPERIENCE.md", "APPLICATION-LIFECYCLE.md"]
ROW = re.compile(r"^\|\s*(SASD-DESKTOP-REQ-\d{3})\s*\|\s*(.*?)\s*\|\s*$")


def generate(repo: Path) -> str:
    profile = repo / "docs" / "20-profiles" / "desktop"
    rows: list[tuple[str, str, str]] = []
    for name in FILES:
        for line in (profile / name).read_text(encoding="utf-8").splitlines():
            match = ROW.match(line)
            if match:
                rows.append((match.group(1), name, match.group(2)))
    rows.sort(key=lambda item: item[0])
    body = ["---", 'title: "Desktop Requirements Index"', "document-id: SASD-REF-DESKTOP-006",
            "document-type: informative", "status: Draft", "version: 0.9.0",
            'standard-version: "1.0"', "language: de", "authoritative: false",
            "owner: SASD Development Standard Maintainer", "last-updated: 2026-07-24",
            "applies-to-quality-levels: [Minimum, Recommended, Production]",
            "applies-to-profiles: [Desktop]", "depends-on: [SASD-PROF-DESKTOP-001]",
            "generated: true", "---", "", "# Desktop Requirements Index", "",
            "> Generated by `tooling/generate-desktop-requirements-index.py`. Do not edit manually.", "",
            f"Total requirements: **{len(rows)}**", "", "| Requirement | Source | Statement |", "|---|---|---|"]
    body += [f"| {rid} | [{name}]({name}) | {statement} |" for rid, name, statement in rows]
    return "\n".join(body) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    repo = Path(__file__).resolve().parents[1]
    target = repo / "docs" / "20-profiles" / "desktop" / "DESKTOP-REQUIREMENTS-INDEX.md"
    expected = generate(repo)
    if args.check:
        if not target.exists() or target.read_text(encoding="utf-8") != expected:
            print(f"FAIL generated file is stale: {target.relative_to(repo)}")
            return 1
        print(f"OK   generated file is current: {target.relative_to(repo)}")
        return 0
    target.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Wrote {target.relative_to(repo)}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
